### ISSUE TITLE
DLL initialisation routine failed in Electron on Windows

### ISSUE THREAD

**Issue by YustinRD** [durs/node-activex#5]
I required winax in Electron on Windows. An error occurs during build.
"A dynamic link library (DLL) initialization routine failed"

**Comment by durs** [comment]
What is the result executing commands in winax folder
node-gyp configure
node-gyp build

**Comment by eugeneshemonaev** [comment]
have the same problem in Electron. node-gyp configure & node-gyp build return ok

```
D:\ARMe\test\node_modules\winax>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\e.shemonaev\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\ARMe\\test\\node_modules\\winax\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\e.shemonaev\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\e.shemonaev\\.node-gyp\\8.1.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\e.shemonaev\\.node-gyp\\8.1.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\e.shemonaev\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\e.shemonaev\\.node-gyp\\8.1.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\ARMe\\test\\node_modules\\winax',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\ARMe\\test\\node_modules\\winax\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

D:\ARMe\test\node_modules\winax>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  win_delay_load_hook.cc
     Creating library D:\ARMe\test\node_modules\winax\build\Release\node_activex.lib and object D:\ARMe\test\node_modul
  es\winax\build\Release\node_activex.exp
  Generating code
  Finished generating code
  node_activex.vcxproj -> D:\ARMe\test\node_modules\winax\build\Release\\node_activex.node
  node_activex.vcxproj -> D:\ARMe\test\node_modules\winax\build\Release\node_activex.pdb (Full PDB)
gyp info ok
```

**Comment by durs** [comment]
It`s OK, dll complete builded - build\Release\node_activex.node
What result of "mocha test/ado.js" ?
Electron uses the same Node version (node@8.1.2 | win32 | x64) ?

**Comment by durs** [comment]
If not mocha installed "node.exe examples/ado.js"

**Comment by eugeneshemonaev** [comment]
electron uses node 7.4.0
mocha was not installed and "node.exe examples/ado.js"  return
```
D:\ARMe\test\node_modules\mocha>node.exe examples/ado.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'D:\ARMe\test\node_modules\mocha\examples\ado.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
then i try to install mocha? but i dont know how to use it. Im newbie in nodejs

**Comment by durs** [comment]
1) mocha not need, but not find module 'D:\ARMe\test\node_modules\moc
ha\examples\ado.js'
before execute  "node.exe examples/ado.js"  set current directory
D:\ARMe\test\node_modules\winax

2) for using native modules need compatible version of node.js
you compile using node 8.1.2 x64 but execute on node 7.4.0 (x64?)




2017-07-05 14:21 GMT+03:00 Eugene Shemonaev <notifications@github.com>:

**Comment by eugeneshemonaev** [comment]
This is what "node.exe examples/ado.js" return
```
D:\ARMe\node_modules\winax>node.exe examples/ado.js
==> Preapre directory and delete DBF file on exists
==> Open connection
ADO version: 10.0
==> Create new DBF file
==> Insert records to DBF
==> Select records from DBF
Result field count: 4
Result record count: -1
> Person: John from London phone: 123-45-67 zip: 14589
> Person: Andrew from Paris phone: 333-44-55 zip: 38215
> Person: Romeo from Rom phone: 222-33-44 zip: 54323
```

Seems like winax works with ADO very good.  But when I reinstall node to 7.4.0 it didnt help with electron. Same error occurs

**Comment by durs** [comment]
Check the match of the processor architecture 64-bit or 32-bit

2017-07-05 16:34 GMT+03:00 Eugene Shemonaev <notifications@github.com>:

**Comment by eugeneshemonaev** [comment]
nodejs 64bit and windows 64bit. I try to launch your example ado.js with electron - same error. Maybe it is error of electron?

**Comment by eugeneshemonaev** [comment]
https://github.com/electron/electron/blob/v0.37.2/docs/tutorial/using-native-node-modules.md#using-native-node-modules this is help me to solve error. But now i have a new one 
`Uncaught Error: Module version mismatch. Expected 50, got 53.`
Version of what module its need?

**Comment by eugeneshemonaev** [comment]
https://stackoverflow.com/questions/39547292/node-module-version-mismatch-expected-50 this is solution for previous error. Now it works!

**Comment by eugeneshemonaev** [comment]
If winax was built using node x64, it doesnt see a 32-bit dll-libraries. A "class is not registered" error is returned. And if you build using node x32, then an error is returned "%1 is not a valid Win32 application". Even `node.exe examples/ado.js` doesnt work

**Comment by durs** [comment]
Это нормальное поведение, в рамках 64 битного процесса невозможно
использовать 32 битные библиотеки и наоборот.
Поэтому если COM модуль реализован как *CLSCTX_INPROC_SERVER *(например
ADO), то необходимо точное соответствие архитектуры, обычно такие
библиотеки собираются отдельно для 32 и 64 битных процессов и
регистрируются в разных ветках реестра. Для вариантов
*CLSCTX_LOCAL_SERVER, **CLSCTX_REMOTE_SERVER* не важно какая архитектура
(например Excel)

2017-07-13 13:44 GMT+03:00 Eugene Shemonaev <notifications@github.com>:

**Comment by eugeneshemonaev** [comment]
Я в это плохо разбираюсь, но выходит раз вылетает ошибка, то необходимый мне модуль существует только в 32-битном виде. Хотя 1С отлично видит этот модуль. Подскажите пожалуйста что мне нужно сделать чтобы все взлетело -  вести разработку в 32-битной системе? Сбилдить приложение электрон   в x32?

**Comment by durs** [comment]
Остаётся только "Сбилдить приложение электрон в x32"
Если 1С видит этот модуль, значит 1С имеет 32 битную архитектуру,
все такие приложения запущенные по по х64 автоматически читают ветку ресстра
HKEY_CLASSES_ROOT\Wow6432Node где  и регистрируется 32 битный COM  модуль.
64 битные приложения ищут регистрацию в корне ветки HKEY_CLASSES_ROOT
Даже утилиты регистрации regsvr32.exe существует 2 вида для 32 и 64 бит




17 июля 2017 г., 9:51 пользователь Eugene Shemonaev <
notifications@github.com> написал:

**Comment by aabuziad** [comment]
Yes you can use electron and winax,

you need to run: 
npm rebuild winax --runtime=electron --target=1.4.3 --disturl=https://atom.io/download/atom-shell --build-from-source

change --target value to your electron version, in my case it's 2.0.2

source: https://www.npmjs.com/package/winax#building
